definitions:
  api.Meta:
    properties:
      displayName:
        type: string
      email:
        type: string
      roles:
        items:
          type: string
        type: array
      runtime:
        type: string
      version:
        type: string
    type: object
  api.SiteInfo:
    properties:
      name:
        type: string
      permissions:
        items:
          type: string
        type: array
      url:
        type: string
    type: object
  api.UserSites:
    properties:
      editable:
        type: boolean
      user:
        type: string
      userSites:
        items:
          $ref: '#/definitions/api.SiteInfo'
        type: array
    type: object
  errors.ProblemDetail:
    properties:
      detail:
        description: Detail is a human-readable explanation specific to this occurrence
          of the problem
        type: string
      instance:
        description: Instance is a URI reference that identifies the specific occurrence
          of the problem
        type: string
      status:
        description: Status is the HTTP status code
        type: integer
      title:
        description: Title is a short, human-readable summary of the problem type
        type: string
      type:
        description: |-
          Type is a URI reference [RFC3986] that identifies the
          problem type.  This specification encourages that, when
          dereferenced, it provide human-readable documentation for the problem
        type: string
    type: object
info:
  contact: {}
  description: The central login for all my applications
  license:
    name: Apache 2.0
    url: https://github.com/bihe/login-go/blob/master/LICENSE
  title: login application
  version: "2.0"
paths:
  /api/v1/appinfo:
    get:
      description: meta-data of the application including authenticated user and version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Meta'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.ProblemDetail'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/errors.ProblemDetail'
      summary: provides information about the application
      tags:
      - appinfo
  /api/v1/sites:
    get:
      description: returns all the sites of the current loged-in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UserSites'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.ProblemDetail'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/errors.ProblemDetail'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.ProblemDetail'
      summary: sites of current user
      tags:
      - sites
    post:
      description: takes a list of sites and stores the supplied sites for the user
      produces:
      - application/json
      responses:
        "201": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.ProblemDetail'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.ProblemDetail'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/errors.ProblemDetail'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.ProblemDetail'
      summary: stores the given sites
      tags:
      - sites
swagger: "2.0"
