definitions:
  appinfo.Meta:
    properties:
      displayName:
        type: string
      email:
        type: string
      roles:
        items:
          type: string
        type: array
      runtime:
        type: string
      version:
        type: string
    type: object
  core.ProblemDetail:
    properties:
      detail:
        description: Detail is a human-readable explanation specific to this occurrence
          of the problem
        type: string
      instance:
        description: Instance is a URI reference that identifies the specific occurrence
          of the problem
        type: string
      status:
        description: Status is the HTTP status code
        type: integer
      title:
        description: Title is a short, human-readable summary of the problem type
        type: string
      type:
        description: |-
          Type is a URI reference [RFC3986] that identifies the
          problem type.  This specification encourages that, when
          dereferenced, it provide human-readable documentation for the problem
        type: string
    type: object
info:
  contact: {}
  description: The central login for all my applications
  license:
    name: Apache 2.0
    url: https://github.com/bihe/login-go/blob/master/LICENSE
  title: login application
  version: "2.0"
paths:
  /api/v1/appinfo:
    get:
      description: meta-data of the application including authenticated user and version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/appinfo.Meta'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/core.ProblemDetail'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/core.ProblemDetail'
      summary: provides information about the application
      tags:
      - appinfo
swagger: "2.0"
